call code --install-extension solnurkarim.html-to-css-autocompletion
call code --install-extension sachinb94.css-tree
call code --install-extension abusaidm.html-snippets
call code --install-extension ahmadawais.shades-of-purple
call code --install-extension burkeholland.simple-react-snippets
call code --install-extension christian-kohler.path-intellisense
call code --install-extension donjayamanne.jquerysnippets
call code --install-extension formulahendry.auto-close-tag
call code --install-extension formulahendry.auto-rename-tag
call code --install-extension hookyqr.beautify
call code --install-extension jeremyrajan.react-component
call code --install-extension mccarter.start-git-bash
call code --install-extension pranaygp.vscode-css-peek
call code --install-extension ritwickdey.liveserver
call code --install-extension thekalinga.bootstrap4-vscode
call code --install-extension ugross.vscode-react-snippets
call code --install-extension vscode-icons-team.vscode-icons
call code --install-extension zignd.html-css-class-completion
call code --install-extension formulahendry.terminal
call code --install-extension johnpapa.angular2
call code --install-extension ktriek.ng-bootstrap-snippets
call code --install-extension eg2.tslint
call code --install-extension steoates.autoimport
